[package]
name = "captain-desktop"
version = "0.2.0"
description = "Captain desktop shell"
authors = ["captain"]
edition = "2021"
license = "MIT"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
sha2 = "0.10"
tauri = { version = "1", features = ["shell-open", "system-tray", "updater"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
